name: Deploy Hello App to Raspberry Pi

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: rpi-hello-api
  HOST: ssh.acentra.org

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 \
          -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest \
          --push .

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PI_HOST }}
        port: 10222
        username: ${{ secrets.PI_USER }}
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          cd ~/rpi-hello-api
          docker compose down
          docker compose up -d --remove-orphans

